name: tests
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read

env:
  DATABASE_URL: file:./test.db
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun db:generate
      - run: bun test:run
